In [22]:
import warnings
warnings.simplefilter(action = 'ignore', category = FutureWarning)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

import dslab

%matplotlib inline
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [23]:
# Import the data sets
house_train = pd.read_csv('train.csv',
                index_col = 0,
                na_values = 'NaN',
                keep_default_na = False)

house_test = pd.read_csv('test.csv',
                  index_col = 0,
                  na_values = 'NaN',
                  keep_default_na = False)

In [24]:
house_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1474 to 1489
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   LotFrontage    1460 non-null   object
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   Alley          1460 non-null   object
 6   LotShape       1460 non-null   object
 7   LandContour    1460 non-null   object
 8   Utilities      1460 non-null   object
 9   LotConfig      1460 non-null   object
 10  LandSlope      1460 non-null   object
 11  Neighborhood   1460 non-null   object
 12  Condition1     1460 non-null   object
 13  Condition2     1460 non-null   object
 14  BldgType       1460 non-null   object
 15  HouseStyle     1460 non-null   object
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   object
 21  RoofMatl       1460 non-null   object
 22  Exterior1st    1460 non-null   object
 23  Exterior2nd    1460 non-null   object
 24  MasVnrType     1460 non-null   object
 25  MasVnrArea     1460 non-null   object
 26  ExterQual      1460 non-null   object
 27  ExterCond      1460 non-null   object
 28  Foundation     1460 non-null   object
 29  BsmtQual       1460 non-null   object
 30  BsmtCond       1460 non-null   object
 31  BsmtExposure   1460 non-null   object
 32  BsmtFinType1   1460 non-null   object
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1460 non-null   object
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   object
 39  HeatingQC      1460 non-null   object
 40  CentralAir     1460 non-null   object
 41  Electrical     1460 non-null   object
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   object
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   object
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    1460 non-null   object
 57  GarageType     1460 non-null   object
 58  GarageYrBlt    1460 non-null   object
 59  GarageFinish   1460 non-null   object
 60  GarageCars     1460 non-null   int64
 61  GarageArea     1460 non-null   int64
 62  GarageQual     1460 non-null   object
 63  GarageCond     1460 non-null   object
 64  PavedDrive     1460 non-null   object
 65  WoodDeckSF     1460 non-null   int64
 66  OpenPorchSF    1460 non-null   int64
 67  EnclosedPorch  1460 non-null   int64
 68  3SsnPorch      1460 non-null   int64
 69  ScreenPorch    1460 non-null   int64
 70  PoolArea       1460 non-null   int64
 71  PoolQC         1460 non-null   object
 72  Fence          1460 non-null   object
 73  MiscFeature    1460 non-null   object
 74  MiscVal        1460 non-null   int64
 75  MoSold         1460 non-null   int64
 76  YrSold         1460 non-null   int64
 77  SaleType       1460 non-null   object
 78  SaleCondition  1460 non-null   object
 79  SalePrice      1460 non-null   int64
dtypes: int64(34), object(46)
memory usage: 923.9+ KB

# Transformations on the Data
## Split the Data into Categorical and Numeric data

In [25]:
# Define variables which are categorical
categorical = ["MSSubClass", "MSZoning", "Street", "Alley", "LotShape","LandContour", "Utilities", 
               "LotConfig", "LandSlope", "Neighborhood","Condition1", "Condition2", "BldgType", "HouseStyle",
               "OverallQual", "OverallCond", "RoofStyle", "RoofMatl", "Exterior1st", "Exterior2nd","MasVnrType",
               "ExterQual", "ExterCond", "Foundation", "BsmtQual","BsmtCond","BsmtExposure", "BsmtFinType1", 
               "BsmtFinType2", "Heating", "HeatingQC","CentralAir", "Electrical", "KitchenQual", "Functional",
               "FireplaceQu","GarageType", "GarageFinish", "GarageQual", "GarageCond", "PavedDrive", "PoolQC", 
               "Fence", "MiscFeature", "SaleType", "SaleCondition"]

# Split training set into categorical and numeric
house_train_cat = house_train[categorical]

house_train_num = house_train.drop(categorical, axis = 1)
# house_train_num currently contains SalePrice so need to remove it and store it in a separate variable
y_train = house_train_num["SalePrice"]
house_train_num = house_train_num.drop("SalePrice", axis = 1)

In [26]:
house_train_cat.info()
house_train_num.info()
y_train

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1474 to 1489
Data columns (total 46 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   Street         1460 non-null   object
 3   Alley          1460 non-null   object
 4   LotShape       1460 non-null   object
 5   LandContour    1460 non-null   object
 6   Utilities      1460 non-null   object
 7   LotConfig      1460 non-null   object
 8   LandSlope      1460 non-null   object
 9   Neighborhood   1460 non-null   object
 10  Condition1     1460 non-null   object
 11  Condition2     1460 non-null   object
 12  BldgType       1460 non-null   object
 13  HouseStyle     1460 non-null   object
 14  OverallQual    1460 non-null   int64
 15  OverallCond    1460 non-null   int64
 16  RoofStyle      1460 non-null   object
 17  RoofMatl       1460 non-null   object
 18  Exterior1st    1460 non-null   object
 19  Exterior2nd    1460 non-null   object
 20  MasVnrType     1460 non-null   object
 21  ExterQual      1460 non-null   object
 22  ExterCond      1460 non-null   object
 23  Foundation     1460 non-null   object
 24  BsmtQual       1460 non-null   object
 25  BsmtCond       1460 non-null   object
 26  BsmtExposure   1460 non-null   object
 27  BsmtFinType1   1460 non-null   object
 28  BsmtFinType2   1460 non-null   object
 29  Heating        1460 non-null   object
 30  HeatingQC      1460 non-null   object
 31  CentralAir     1460 non-null   object
 32  Electrical     1460 non-null   object
 33  KitchenQual    1460 non-null   object
 34  Functional     1460 non-null   object
 35  FireplaceQu    1460 non-null   object
 36  GarageType     1460 non-null   object
 37  GarageFinish   1460 non-null   object
 38  GarageQual     1460 non-null   object
 39  GarageCond     1460 non-null   object
 40  PavedDrive     1460 non-null   object
 41  PoolQC         1460 non-null   object
 42  Fence          1460 non-null   object
 43  MiscFeature    1460 non-null   object
 44  SaleType       1460 non-null   object
 45  SaleCondition  1460 non-null   object
dtypes: int64(3), object(43)
memory usage: 536.1+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1474 to 1489
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   LotFrontage    1460 non-null   object
 1   LotArea        1460 non-null   int64
 2   YearBuilt      1460 non-null   int64
 3   YearRemodAdd   1460 non-null   int64
 4   MasVnrArea     1460 non-null   object
 5   BsmtFinSF1     1460 non-null   int64
 6   BsmtFinSF2     1460 non-null   int64
 7   BsmtUnfSF      1460 non-null   int64
 8   TotalBsmtSF    1460 non-null   int64
 9   1stFlrSF       1460 non-null   int64
 10  2ndFlrSF       1460 non-null   int64
 11  LowQualFinSF   1460 non-null   int64
 12  GrLivArea      1460 non-null   int64
 13  BsmtFullBath   1460 non-null   int64
 14  BsmtHalfBath   1460 non-null   int64
 15  FullBath       1460 non-null   int64
 16  HalfBath       1460 non-null   int64
 17  BedroomAbvGr   1460 non-null   int64
 18  KitchenAbvGr   1460 non-null   int64
 19  TotRmsAbvGrd   1460 non-null   int64
 20  Fireplaces     1460 non-null   int64
 21  GarageYrBlt    1460 non-null   object
 22  GarageCars     1460 non-null   int64
 23  GarageArea     1460 non-null   int64
 24  WoodDeckSF     1460 non-null   int64
 25  OpenPorchSF    1460 non-null   int64
 26  EnclosedPorch  1460 non-null   int64
 27  3SsnPorch      1460 non-null   int64
 28  ScreenPorch    1460 non-null   int64
 29  PoolArea       1460 non-null   int64
 30  MiscVal        1460 non-null   int64
 31  MoSold         1460 non-null   int64
 32  YrSold         1460 non-null   int64
dtypes: int64(30), object(3)
memory usage: 387.8+ KB

Order
1474    208500
1860    181500
1444    223500
2858    140000
1101    250000
         ...
1756    175000
20      210000
296     266500
127     142125
1489    147500
Name: SalePrice, Length: 1460, dtype: int64

## Working with Numeric Variables

From the exploratory analysis of the data, there appeared to be several variables which were classified as numeric (as provided in the data description .txt file), but is more appropriate to be labelled as a categorical variable. I believe this to be the case as these variables have a very limited range of values, with majority of observations falling into discrete categories.

These variables should be identified (ideally automatically) and removed from the 'house_train_num' list and moved into 'house_train_cat'. I will choose having at least 10 unique values to be the minimum benchmark that classifies a variable to be numeric (i.e. any variable with less than 10 unique values will be classified as categorical).

In [28]:
# Obtain all variables in house_train_num which should be labelled as a categorical variable
numCat = [i for i in house_train_num.columns if len(house_train[i].unique()) < 10]
numCat

['BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'Fireplaces',
 'GarageCars',
 'PoolArea',
 'YrSold']

In [29]:
# Concatenate numCat onto categorical
categorical += numCat
categorical

['MSSubClass',
 'MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'Fireplaces',
 'GarageCars',
 'PoolArea',
 'YrSold']

In [168]:
# Update house_train_cat and house_train_num with for new variables
house_train_cat = house_train[categorical]

house_train_num = house_train.drop(categorical, axis = 1)
house_train_num = house_train_num.drop("SalePrice", axis = 1)

In [169]:
house_train_cat.info()
house_train_num.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1474 to 1489
Data columns (total 56 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   Street         1460 non-null   object
 3   Alley          1460 non-null   object
 4   LotShape       1460 non-null   object
 5   LandContour    1460 non-null   object
 6   Utilities      1460 non-null   object
 7   LotConfig      1460 non-null   object
 8   LandSlope      1460 non-null   object
 9   Neighborhood   1460 non-null   object
 10  Condition1     1460 non-null   object
 11  Condition2     1460 non-null   object
 12  BldgType       1460 non-null   object
 13  HouseStyle     1460 non-null   object
 14  OverallQual    1460 non-null   int64
 15  OverallCond    1460 non-null   int64
 16  RoofStyle      1460 non-null   object
 17  RoofMatl       1460 non-null   object
 18  Exterior1st    1460 non-null   object
 19  Exterior2nd    1460 non-null   object
 20  MasVnrType     1460 non-null   object
 21  ExterQual      1460 non-null   object
 22  ExterCond      1460 non-null   object
 23  Foundation     1460 non-null   object
 24  BsmtQual       1460 non-null   object
 25  BsmtCond       1460 non-null   object
 26  BsmtExposure   1460 non-null   object
 27  BsmtFinType1   1460 non-null   object
 28  BsmtFinType2   1460 non-null   object
 29  Heating        1460 non-null   object
 30  HeatingQC      1460 non-null   object
 31  CentralAir     1460 non-null   object
 32  Electrical     1460 non-null   object
 33  KitchenQual    1460 non-null   object
 34  Functional     1460 non-null   object
 35  FireplaceQu    1460 non-null   object
 36  GarageType     1460 non-null   object
 37  GarageFinish   1460 non-null   object
 38  GarageQual     1460 non-null   object
 39  GarageCond     1460 non-null   object
 40  PavedDrive     1460 non-null   object
 41  PoolQC         1460 non-null   object
 42  Fence          1460 non-null   object
 43  MiscFeature    1460 non-null   object
 44  SaleType       1460 non-null   object
 45  SaleCondition  1460 non-null   object
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  Fireplaces     1460 non-null   int64
 53  GarageCars     1460 non-null   int64
 54  PoolArea       1460 non-null   int64
 55  YrSold         1460 non-null   int64
dtypes: int64(13), object(43)
memory usage: 690.2+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1474 to 1489
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   LotFrontage    1460 non-null   object
 1   LotArea        1460 non-null   int64
 2   YearBuilt      1460 non-null   int64
 3   YearRemodAdd   1460 non-null   int64
 4   MasVnrArea     1460 non-null   object
 5   BsmtFinSF1     1460 non-null   int64
 6   BsmtFinSF2     1460 non-null   int64
 7   BsmtUnfSF      1460 non-null   int64
 8   TotalBsmtSF    1460 non-null   int64
 9   1stFlrSF       1460 non-null   int64
 10  2ndFlrSF       1460 non-null   int64
 11  LowQualFinSF   1460 non-null   int64
 12  GrLivArea      1460 non-null   int64
 13  TotRmsAbvGrd   1460 non-null   int64
 14  GarageYrBlt    1460 non-null   object
 15  GarageArea     1460 non-null   int64
 16  WoodDeckSF     1460 non-null   int64
 17  OpenPorchSF    1460 non-null   int64
 18  EnclosedPorch  1460 non-null   int64
 19  3SsnPorch      1460 non-null   int64
 20  ScreenPorch    1460 non-null   int64
 21  MiscVal        1460 non-null   int64
 22  MoSold         1460 non-null   int64
dtypes: int64(20), object(3)
memory usage: 313.8+ KB

We shall make copies of these two dataframes which will act as the 'cleaned' dataframe. This allows us to preserve the 'before' values.

In [172]:
house_train_num_cleaned = house_train_num.copy()
house_train_cat_cleaned = house_train_cat.copy()

Of the remaining numerical variables, it is important to remove any skew in the data. To do this, we will apply a log (natural log) transformation on any numeric variables with a strong right skew.

However before we do that, we can observe that there are three numeric variables which are stored as type 'Object'.

In [173]:
house_train_num[["LotFrontage", "MasVnrArea", "GarageYrBlt"]]

      LotFrontage MasVnrArea GarageYrBlt
Order
1474           65        196        2003
1860           80          0        1976
1444           68        162        2001
2858           60          0        1998
1101           84        350        2000
...           ...        ...         ...
1756           62          0        1999
20             85        119        1978
296            66          0        1941
127            68          0        1950
1489           75          0        1965

[1460 rows x 3 columns]

From the exploratory analysis, we know that the reasoning behind this data type is because all three of these variables contain 'NA' values, and so they must be dealt with before we're able to convert them into type int.

In [174]:
# Change LotFrontage NA values into 0
house_train_num_cleaned["LotFrontage"] = house_train_num_cleaned["LotFrontage"].str.replace('NA', '0').astype(int)

In [175]:
# Impute MasVnrArea NA values to be equal to the median value
MasVnrArea_med = str(int(house_train_num_cleaned.MasVnrArea[house_train.MasVnrArea.str.contains("NA") == False].median()))
house_train_num_cleaned["MasVnrArea"] = house_train_num_cleaned["MasVnrArea"].str.replace('NA', MasVnrArea_med).astype(float)

house_train_num_cleaned["MasVnrArea"] = house_train_num_cleaned["MasVnrArea"].astype(int)

In [176]:
house_train_num_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1474 to 1489
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   LotFrontage    1460 non-null   int32
 1   LotArea        1460 non-null   int64
 2   YearBuilt      1460 non-null   int64
 3   YearRemodAdd   1460 non-null   int64
 4   MasVnrArea     1460 non-null   int32
 5   BsmtFinSF1     1460 non-null   int64
 6   BsmtFinSF2     1460 non-null   int64
 7   BsmtUnfSF      1460 non-null   int64
 8   TotalBsmtSF    1460 non-null   int64
 9   1stFlrSF       1460 non-null   int64
 10  2ndFlrSF       1460 non-null   int64
 11  LowQualFinSF   1460 non-null   int64
 12  GrLivArea      1460 non-null   int64
 13  TotRmsAbvGrd   1460 non-null   int64
 14  GarageYrBlt    1460 non-null   object
 15  GarageArea     1460 non-null   int64
 16  WoodDeckSF     1460 non-null   int64
 17  OpenPorchSF    1460 non-null   int64
 18  EnclosedPorch  1460 non-null   int64
 19  3SsnPorch      1460 non-null   int64
 20  ScreenPorch    1460 non-null   int64
 21  MiscVal        1460 non-null   int64
 22  MoSold         1460 non-null   int64
dtypes: int32(2), int64(20), object(1)
memory usage: 302.3+ KB

Regarding the final GarageYrBlt variable, it's noticed that all variables (numerical and categorical) which involve the garages have 81 NA or 0 values (most likely due to these 81 properties not having a garage). As such, it is likely simplest to remove these 81 observations from the training data set. 

Below we shall check that the 'Order' is the same between the Garage- variables before removing them from the data set.

In [177]:
# Check order for GarageYrBlt (numeric variable) with NA values
house_train_num_cleaned[house_train_num_cleaned["GarageYrBlt"].str.match("NA")]

,LotFrontage,LotArea,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,...,TotRmsAbvGrd,GarageYrBlt,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,MiscVal,MoSold
Order,,,,,,,,,,,,,,,,,,,,,
1501,65,6040,1955,1955,0,0,0,0,0,1152,...,6,NA,0,0,0,0,0,0,0,6
713,33,4456,1920,2008,0,0,0,736,736,736,...,8,NA,0,0,0,102,0,0,0,6
218,72,10778,1968,1968,0,0,0,1768,1768,1768,...,8,NA,0,0,0,0,0,0,0,4
943,105,8470,1915,1982,0,0,0,1013,1013,1013,...,6,NA,0,0,0,156,0,0,0,10
2127,60,8070,1994,1995,0,588,0,402,990,990,...,5,NA,0,0,0,0,0,0,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1319,50,5250,1872,1987,0,259,0,425,684,938,...,8,NA,0,0,54,20,0,0,0,12
984,0,8780,1985,1985,0,625,0,208,833,833,...,5,NA,0,0,0,0,0,0,0,3
2917,21,1533,1970,1970,0,553,0,77,630,630,...,3,NA,0,0,0,0,0,0,0,8
393,60,9000,1974,1974,0,0,0,896,896,896,...,8,NA,0,32,45,0,0,0,0,9
2908,90,17217,2006,2006,0,0,0,1140,1140,1140,...,6,NA,0,36,56,0,0,0,0,7

In [178]:
# Check order for GarageType (categorical variable)
house_train_cat_cleaned[house_train_cat_cleaned["GarageType"].str.match("NA")]

,MSSubClass,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,...,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,Fireplaces,GarageCars,PoolArea,YrSold
Order,,,,,,,,,,,,,,,,,,,,,
1501,90,RL,Pave,NA,Reg,Lvl,AllPub,Inside,Gtl,Edwards,...,0,0,2,0,2,2,0,0,0,2008
713,190,RM,Pave,NA,Reg,Lvl,AllPub,Inside,Gtl,OldTown,...,0,0,2,0,2,3,0,0,0,2009
218,90,RL,Pave,NA,Reg,Lvl,AllPub,Inside,Gtl,Sawyer,...,0,0,2,0,4,2,0,0,0,2010
943,50,C (all),Pave,NA,IR1,Lvl,AllPub,Corner,Gtl,IDOTRR,...,0,0,1,0,2,1,0,0,0,2009
2127,20,RL,Pave,NA,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,...,1,0,1,0,3,1,0,0,0,2007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1319,70,RM,Pave,Pave,Reg,Lvl,AllPub,Inside,Gtl,OldTown,...,0,0,2,0,4,1,0,0,0,2008
984,20,RL,Pave,NA,IR1,Lvl,AllPub,Corner,Gtl,Mitchel,...,1,0,1,0,3,1,0,0,0,2009
2917,180,RM,Pave,NA,Reg,Lvl,AllPub,Inside,Gtl,MeadowV,...,1,0,1,0,1,1,0,0,0,2006
393,90,RL,Pave,NA,Reg,Lvl,AllPub,FR2,Gtl,NAmes,...,0,0,2,2,4,2,0,0,0,2009
2908,20,RL,Pave,NA,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,...,0,0,1,0,3,1,0,0,0,2006

The 'Order' values appear to match, and so it is safe to remove these rows that correspond to these Orders.

In [181]:
# Remove observations with no garages from house_train_num_cleaned
house_train_num_cleaned = house_train_num_cleaned[~house_train_num_cleaned["GarageYrBlt"].str.match("NA")]

# Remove observations with no garages from house_train_cat_cleaned
house_train_cat_cleaned = house_train_cat_cleaned[~house_train_cat_cleaned["GarageType"].str.match("NA")]

In [ ]:
# Convert GarageYrBlt into int (from an object)
house_train_num_cleaned["GarageYrBlt"].astype(int)

In [153]:
# Check skew for each numeric variable
house_train_num_cleaned.skew(axis = 0).sort_values(ascending = False)

MiscVal          24.476794
LotArea          12.207688
3SsnPorch        10.304342
LowQualFinSF      9.011341
BsmtFinSF2        4.255261
ScreenPorch       4.122214
EnclosedPorch     3.089872
MasVnrArea        2.677616
OpenPorchSF       2.364342
BsmtFinSF1        1.685503
WoodDeckSF        1.541376
TotalBsmtSF       1.524255
1stFlrSF          1.376757
GrLivArea         1.366560
BsmtUnfSF         0.920268
2ndFlrSF          0.813030
TotRmsAbvGrd      0.676341
LotFrontage       0.267822
MoSold            0.212053
GarageArea        0.179981
YearRemodAdd     -0.503562
YearBuilt        -0.613461
dtype: float64

In [42]:
from dslab.visualization.visualize import distribution

## Working with Categorical Variables

Having explored through all the categorical variables (as shown in **III. Explore the data***), we are able to see that there are many variables where the most common category makes up the vast majority of the categories chosen for each house (e.g. Condition2 where the most popoular category has 1445 labels, and 6 labels for the next most popular).

Variables such as this have extremely low variance, and as much may be of worth to remove them from the data set to not speed up the modelling process and help prevent overfitting. 

I will choose 90% of all votes as the threshold value for removal (i.e. if a given category makes up at least 90% of all votes it will be removed)

In [32]:
# Script to help remove categorical variables where the most popular category makes up at least 90% of all options.

# Define new list to store categorical variables
categorical_new = []

# Loop through every categorical variable
for i in categorical:
#     print(house_train_cat[i].value_counts(normalize = True))
    if (house_train_cat[i].value_counts(normalize = True).iloc[0] < 0.90):
        categorical_new.append(i)
    
categorical_new

['MSSubClass',
 'MSZoning',
 'LotShape',
 'LandContour',
 'LotConfig',
 'Neighborhood',
 'Condition1',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'RoofStyle',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'HeatingQC',
 'KitchenQual',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'Fence',
 'SaleType',
 'SaleCondition',
 'BsmtFullBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'Fireplaces',
 'GarageCars',
 'YrSold']

In [33]:
print("Old number of categorical variables:", len(categorical), "\n",
      "New number of categorical variables:", len(categorical_new))

Old number of categorical variables: 56
 New number of categorical variables: 39

In [34]:
# Apply the new categorical variables onto house_train_cat
house_train_cat = house_train[categorical_new]
house_train_cat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1474 to 1489
Data columns (total 39 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   LotShape       1460 non-null   object
 3   LandContour    1460 non-null   object
 4   LotConfig      1460 non-null   object
 5   Neighborhood   1460 non-null   object
 6   Condition1     1460 non-null   object
 7   BldgType       1460 non-null   object
 8   HouseStyle     1460 non-null   object
 9   OverallQual    1460 non-null   int64
 10  OverallCond    1460 non-null   int64
 11  RoofStyle      1460 non-null   object
 12  Exterior1st    1460 non-null   object
 13  Exterior2nd    1460 non-null   object
 14  MasVnrType     1460 non-null   object
 15  ExterQual      1460 non-null   object
 16  ExterCond      1460 non-null   object
 17  Foundation     1460 non-null   object
 18  BsmtQual       1460 non-null   object
 19  BsmtCond       1460 non-null   object
 20  BsmtExposure   1460 non-null   object
 21  BsmtFinType1   1460 non-null   object
 22  BsmtFinType2   1460 non-null   object
 23  HeatingQC      1460 non-null   object
 24  KitchenQual    1460 non-null   object
 25  FireplaceQu    1460 non-null   object
 26  GarageType     1460 non-null   object
 27  GarageFinish   1460 non-null   object
 28  GarageQual     1460 non-null   object
 29  Fence          1460 non-null   object
 30  SaleType       1460 non-null   object
 31  SaleCondition  1460 non-null   object
 32  BsmtFullBath   1460 non-null   int64
 33  FullBath       1460 non-null   int64
 34  HalfBath       1460 non-null   int64
 35  BedroomAbvGr   1460 non-null   int64
 36  Fireplaces     1460 non-null   int64
 37  GarageCars     1460 non-null   int64
 38  YrSold         1460 non-null   int64
dtypes: int64(10), object(29)
memory usage: 456.2+ KB

In [161]:
house_train_cat["GarageType"].str.find("NA")
# house_train_cat["GarageFinish"].value_counts()

Order
1474   -1
1860   -1
1444   -1
2858   -1
1101   -1
       ..
1756   -1
20     -1
296    -1
127    -1
1489   -1
Name: GarageType, Length: 1460, dtype: int64

As seen above, 17 variables categorical variables were removed.

In addition, for categorical variables to be best utilised, it is good to convert them into a sparse matrix through one-hot encoding

In [35]:
from sklearn.preprocessing import OneHotEncoder

oneHot = OneHotEncoder(sparse = False)
house_train_cat_oneHot = oneHot.fit_transform(house_train_cat)
house_train_cat_df = pd.DataFrame(house_train_cat_oneHot, columns = oneHot.get_feature_names())
house_train_cat_df

,x0_20,x0_30,x0_40,x0_45,x0_50,x0_60,x0_70,x0_75,x0_80,x0_85,...,x37_0,x37_1,x37_2,x37_3,x37_4,x38_2006,x38_2007,x38_2008,x38_2009,x38_2010
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1456,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1457,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1458,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1459,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0